// Generated by CoffeeScript 1.3.3

$(function() {
  var $about_area, $contact_area, $mainHeader, $services_area, $why_area, document;
  document = $(window.document);
  $services_area = $('#services');
  $about_area = $('#about');
  $why_area = $('#why');
  $contact_area = $('#contact');
  $mainHeader = $('#main-header');
  $(document).scroll(function() {
    var marginTop, sTop;
    sTop = document.scrollTop();
    marginTop = 150;
    if (sTop >= $services_area.offset().top - marginTop && sTop <= $about_area.offset().top - marginTop) {
      return $mainHeader.removeAttr('class').addClass('highlight services-area');
    } else if (sTop >= $about_area.offset().top - marginTop && sTop <= $why_area.offset().top - marginTop) {
      return $mainHeader.removeAttr('class').addClass('highlight about-area');
    } else if (sTop >= $why_area.offset().top - marginTop && sTop <= $contact_area.offset().top - marginTop) {
      return $mainHeader.removeAttr('class').addClass('highlight why-area');
    } else {
      return $mainHeader.removeAttr('class');
    }
  });
  $(".main-menu-item a", $mainHeader).click(function(e) {
    e.preventDefault();
    return $('html,body').animate({
      scrollTop: $(this.hash).offset().top
    }, 500);
  });
  $('.description', '.team-member').addClass('excerpt');
  return $('a.more-content', '.team-member').click(function(e) {
    e.preventDefault();
    return $(this).closest('.team-member').find('.description').toggleClass('excerpt');
  });
});
