// Generated by CoffeeScript 1.3.3

$(function() {
  var $about_area, $contact_area, $mainHeader, $services_area, $why_area, changeForm, contact_state, current_area, document, marginTop, scrollToNewArea, setHeaderBarState;
  document = $(window.document);
  $services_area = $('#services');
  $about_area = $('#about');
  $why_area = $('#why');
  $contact_area = $('#contact');
  $mainHeader = $('#main-header');
  marginTop = 150;
  contact_state = 'contact';
  current_area = '#home';
  setHeaderBarState = function(area) {
    $mainHeader.removeAttr('class');
    $('li', $mainHeader).removeClass('current');
    current_area = area;
    switch (area) {
      case '#services':
        $mainHeader.addClass('highlight services-area');
        return $('#services-item').addClass('current');
      case '#about':
        $mainHeader.addClass('highlight about-area');
        return $('#about-item').addClass('current');
      case '#why':
        $mainHeader.addClass('highlight why-area');
        return $('#why-item').addClass('current');
      case '#home':
      case '#sim':
        return $('#home-item').addClass('current');
      default:
        switch (contact_state) {
          case 'orcamento':
            return $('#orcamento-item').addClass('current');
          case 'join':
            return $('#join-item').addClass('current');
          default:
            return $('#contact-item').addClass('current');
        }
    }
  };
  scrollToNewArea = function(area) {
    if (area !== current_area) {
      return setHeaderBarState(area);
    }
  };
  $(document).scroll(function() {
    var sTop;
    sTop = document.scrollTop();
    if (sTop <= $services_area.offset().top - marginTop) {
      return scrollToNewArea('#home');
    } else if (sTop >= $services_area.offset().top - marginTop && sTop <= $about_area.offset().top - marginTop) {
      return scrollToNewArea('#services');
    } else if (sTop >= $about_area.offset().top - marginTop && sTop <= $why_area.offset().top - marginTop) {
      return scrollToNewArea('#about');
    } else if (sTop >= $why_area.offset().top - marginTop && sTop <= $contact_area.offset().top - marginTop) {
      return scrollToNewArea('#why');
    } else {
      return scrollToNewArea('#contact');
    }
  });
  $("a[href^=#][href!=#]").click(function(e) {
    var hash;
    hash = this.hash;
    return $('html,body', document).animate({
      scrollTop: $(this.hash).offset().top
    }, 500, function() {
      return setHeaderBarState(hash);
    });
  });
  $('.team-member').addClass('excerpt');
  $('a.more-content', '.team-member').click(function(e) {
    var $parent, $scrollToThis;
    e.preventDefault();
    $parent = $(this).closest('.team-member');
    $parent.toggleClass('excerpt');
    if ($parent.hasClass('excerpt')) {
      $scrollToThis = $parent;
    } else {
      $scrollToThis = $parent.find('.description').first();
    }
    return $('html,body', document).animate({
      scrollTop: $scrollToThis.offset().top - marginTop + 30
    }, 500);
  });
  changeForm = function() {
    $('#contact div').hide();
    return $('#form-' + contact_state).fadeIn();
  };
  return $('.contact-menu-link').click(function() {
    var new_data;
    new_data = String($(this).data('form'));
    if (contact_state !== new_data) {
      contact_state = new_data;
      setHeaderBarState('#contact');
      return changeForm();
    }
  });
});
